name: aarch64

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2.0.9
      
      with:
        arch: aarch64
        distro: ubuntu18.04
        run: |
          cmake -E make_directory ${{github.workspace}}/build
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          cmake --build . --config $BUILD_TYPE
